"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip() or 'django-insecure-vetal-sand-solutions-fallback-key-for-serverless-2026'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

def _clean_host(host_str):
    if not host_str:
        return ''
    host_str = host_str.strip().strip('\'"')
    if '://' in host_str:
        host_str = host_str.split('://', 1)[1]
    host_str = host_str.split('/')[0].split('?')[0].split('#')[0].strip()
    if ':' in host_str and not host_str.startswith('['):
        host_str = host_str.split(':', 1)[0].strip()
    return host_str.lower()

_DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'testserver',
    '[::1]',
    'vetal-sand-solutions.vercel.app',
    '.vercel.app',
    '.now.sh',
]

_raw_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = list(_DEFAULT_ALLOWED_HOSTS)

if _raw_allowed_hosts.strip():
    for _host_entry in _raw_allowed_hosts.split(','):
        _cleaned = _clean_host(_host_entry)
        if _cleaned and _cleaned not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_cleaned)

for _vercel_env_key in ('VERCEL_URL', 'VERCEL_PROJECT_PRODUCTION_URL', 'VERCEL_BRANCH_URL'):
    _v_host = os.environ.get(_vercel_env_key)
    if _v_host:
        _cleaned = _clean_host(_v_host)
        if _cleaned and _cleaned not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_cleaned)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    # Our Apps
    'core',
    'products',
    'accounts',
    'cart',
    'orders',
    'payments',
    'enquiries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
                'products.context_processors.wishlist_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

IS_VERCEL = bool(
    os.environ.get('VERCEL')
    or os.environ.get('VERCEL_ENV')
    or os.environ.get('VERCEL_URL')
)

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }
    
else:
    if IS_VERCEL:
        import shutil
        tmp_db = Path('/tmp') / 'db.sqlite3'
        source_db = BASE_DIR / 'db.sqlite3'
        if not tmp_db.exists() and source_db.exists():
            try:
                shutil.copy2(source_db, tmp_db)
            except Exception:
                pass
        db_path = tmp_db
    else:
        db_path = BASE_DIR / 'db.sqlite3'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
_cloudinary_placeholders = {'', 'value', 'your-cloud-name', 'your-api-key', 'your-api-secret'}
_DEFAULT_CLOUD_NAME = 'gmswmfkp'
_raw_cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME', '').strip()
if not _raw_cloud_name or _raw_cloud_name.lower() in _cloudinary_placeholders:
    _resolved_cloud_name = _DEFAULT_CLOUD_NAME
else:
    _resolved_cloud_name = _raw_cloud_name

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _resolved_cloud_name,
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '').strip(),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', '').strip(),
}
CLOUDINARY_CONFIGURED = (
    bool(CLOUDINARY_STORAGE['CLOUD_NAME'])
    and bool(CLOUDINARY_STORAGE['API_KEY'])
    and bool(CLOUDINARY_STORAGE['API_SECRET'])
    and CLOUDINARY_STORAGE['API_KEY'].lower() not in _cloudinary_placeholders
    and CLOUDINARY_STORAGE['API_SECRET'].lower() not in _cloudinary_placeholders
)

# Always configure Cloudinary with the resolved cloud name and HTTPS
cloudinary.config(
    cloud_name=_resolved_cloud_name,
    api_key=CLOUDINARY_STORAGE['API_KEY'] or None,
    api_secret=CLOUDINARY_STORAGE['API_SECRET'] or None,
    secure=True,
)

if CLOUDINARY_CONFIGURED:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Safe guard: prevent CloudinaryResource.url from raising uncaught ValueError in templates
# and ensure secure HTTPS URLs with direct fallback
try:
    from cloudinary import CloudinaryResource
    _orig_cr_url = CloudinaryResource.url

    def _safe_cr_url(self):
        try:
            url = _orig_cr_url.fget(self)
            if url:
                if url.startswith('http://'):
                    url = 'https://' + url[7:]
                if not url.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')):
                    url = f'{url}.jpg'
                return url
        except Exception:
            pass

        # Fallback to direct URL construction if needed
        public_id = getattr(self, 'public_id', None)
        if public_id:
            version = getattr(self, 'version', None)
            v_part = f'v{version}/' if version else ''
            fmt = getattr(self, 'format', None) or 'jpg'
            ext = f'.{fmt}' if not str(public_id).lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')) else ''
            return f'https://res.cloudinary.com/{_resolved_cloud_name}/image/upload/{v_part}{public_id}{ext}'
        return ''

    CloudinaryResource.url = property(_safe_cr_url)
except Exception:
    pass


_razorpay_placeholders = {'', 'value', 'your-key-id', 'your-key-secret', 'rzp_test_xxx', 'rzp_live_xxx'}

def _get_first_env(*keys, default=''):
    for k in keys:
        val = os.environ.get(k)
        if val is not None:
            cleaned = str(val).strip().strip('\'"')
            if cleaned and cleaned.lower() not in _razorpay_placeholders:
                return cleaned
    return default

RAZORPAY_KEY_ID = _get_first_env(
    'RAZORPAY_KEY_ID', 'RAZORPAY_KEY', 'RAZORPAY_API_KEY',
    'RAZORPAY_PUBLIC_KEY', 'RZP_KEY_ID', 'RZP_KEY'
)
RAZORPAY_KEY_SECRET = _get_first_env(
    'RAZORPAY_KEY_SECRET', 'RAZORPAY_SECRET', 'RAZORPAY_API_SECRET',
    'RAZORPAY_PRIVATE_KEY', 'RAZORPAY_SECRET_KEY', 'RZP_KEY_SECRET', 'RZP_SECRET'
)
RAZORPAY_CURRENCY = os.environ.get('RAZORPAY_CURRENCY', 'INR').strip().strip('\'"') or 'INR'

# Handle test mode: check explicit setting or infer from key prefix
_raw_test_mode = os.environ.get('RAZORPAY_TEST_MODE', '').strip().lower()
if _raw_test_mode in {'1', 'true', 'yes', 'on'}:
    RAZORPAY_TEST_MODE = True
elif _raw_test_mode in {'0', 'false', 'no', 'off'}:
    RAZORPAY_TEST_MODE = False
else:
    # Auto-detect from key prefix: if key starts with rzp_test_, default to True; if rzp_live_, False
    RAZORPAY_TEST_MODE = not RAZORPAY_KEY_ID.startswith('rzp_live_')

RAZORPAY_CONFIGURED = (
    bool(RAZORPAY_KEY_ID)
    and bool(RAZORPAY_KEY_SECRET)
    and RAZORPAY_KEY_ID.lower() not in _razorpay_placeholders
    and RAZORPAY_KEY_SECRET.lower() not in _razorpay_placeholders
    and (
        (RAZORPAY_TEST_MODE and RAZORPAY_KEY_ID.startswith('rzp_test_'))
        or (not RAZORPAY_TEST_MODE and (RAZORPAY_KEY_ID.startswith('rzp_live_') or RAZORPAY_KEY_ID.startswith('rzp_test_')))
    )
)

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT') or '587')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
COMPANY_NOTIFICATION_EMAIL = os.environ.get('COMPANY_NOTIFICATION_EMAIL', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST else 'django.core.mail.backends.console.EmailBackend',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

def _clean_origin(origin_str):
    if not origin_str:
        return ''
    origin_str = origin_str.strip().strip('\'"')
    if not origin_str.startswith(('http://', 'https://')):
        origin_str = f'https://{origin_str}'
    parts = origin_str.split('://', 1)
    scheme = parts[0].lower()
    host_part = parts[1].split('/')[0].split('?')[0].split('#')[0].strip().lower()
    return f'{scheme}://{host_part}'

_DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'https://vetal-sand-solutions.vercel.app',
    'https://*.vercel.app',
    'https://*.now.sh',
]

_raw_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = list(_DEFAULT_CSRF_TRUSTED_ORIGINS)

if _raw_csrf.strip():
    for _origin in _raw_csrf.split(','):
        _cleaned_orig = _clean_origin(_origin)
        if _cleaned_orig and _cleaned_orig not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_cleaned_orig)

for _vercel_env_key in ('VERCEL_URL', 'VERCEL_PROJECT_PRODUCTION_URL', 'VERCEL_BRANCH_URL'):
    _v_origin = os.environ.get(_vercel_env_key)
    if _v_origin:
        _cleaned_orig = _clean_origin(_v_origin)
        if _cleaned_orig and _cleaned_orig not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_cleaned_orig)

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in {'1', 'true', 'yes', 'on'}
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS') or '0')