# Generated by Django 6.0.3 on 2026-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the product price in INR. Leave blank if pricing is available only on request.', max_digits=12, null=True),
        ),
    ]
